version: '3.9'

services:
  db:
    image: postgres:15
    container_name: comment-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: comments
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    container_name: nest-comment-app
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    restart: always

volumes:
  pgdata:
